name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: '.release-please-config.json'

  upload-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build your distribution (adjust as needed)
      - name: Build Distribution
        run: |
          npm ci
          npm run build

      # Zip everything except src, test, and .git* files
      - name: Zip Node package (excluding src)
        run: |
          zip -r dist.zip . -x "src/*" "test/*" ".git*" ".github/*" "node_modules/*"

      # Get latest release upload_url
      - name: Get latest release upload_url
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput('upload_url', latestRelease.upload_url);

      # Upload dist.zip as a release asset
      - name: Upload dist to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
